### ISSUE TITLE
DiscordAPI

### ISSUE THREAD

**Issue by Wiktorsson** [Wiktorsson/DiscordGyA#1]
Kommandon
- [x] stoppa uppspelning
- [x] lägg till bot till voice channel 
- [x] ta bort bot från voice channel
- [x] pausa uppspelning
- [x] starta uppspelning
- [x] lägg till låt i playlist baserat på youtube url
- [x] lägg till låg i playlist baserat på låtnamn
- [ ] hoppa till nästa låt

**Comment by JohanG2012** [comment]
Du kommer troligvis behöva ta hjälp av dessa för dom punkter du har kvar. 

[DiscordJs Dokumentation](https://discord.js.org/#/docs/main/stable/general/welcome)

[Voice delen i dokumentationen för DiscordJS](https://github.com/discordjs/discord.js/blob/master/docs/topics/voice.md)

[NodeJS Event Emitters Tutorial](https://appdividend.com/2017/10/16/node-js-events-eventemitter-tutorial-example-scratch/)

[Async, Await & Fetch](https://webbutveckling2.gitbook.io/hem/resurser/2.2-async-and-await)
