### ISSUE TITLE
Organisera kodbasen

### ISSUE THREAD

**Issue by JohanG2012** [Wiktorsson/DiscordGyA#24]
Du har flera funktioner i din `bot.js` som är relaterade till YouTube eller kommandon. Dessa skulle du kunna flytta ut till egna filer/moduler så som du gjort med twitter. Till exempel `youtube.js` och `kommandon.js` för att hålla din kodbas organiserat allt eftersom den växer. Och sedan importerar du dem till din `bot.js`

**Comment by Wiktorsson** [comment]
yikes
