### ISSUE TITLE
TwitterAPI

### ISSUE THREAD

**Issue by Wiktorsson** [Wiktorsson/DiscordGyA#3]
- [ ] Varje vecka tweeta ut mest spelade låtarna

**Comment by JohanG2012** [comment]
För att lyckas med denna så behöver du:

- [x] Ett Twitter konto
- [x] Registrera API Keys -> https://developer.twitter.com/en/apps/
- [x] Lära dig hur du authenticate över OAuth https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request och https://developer.twitter.com/en/docs/basics/authentication/guides/creating-a-signature.html
- [ ] Dokumentationen för API:et https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update

Användbara resurser.

- [ ] Tid i epoch format https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
- [ ] URI Encode https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
- [ ] Nodejs Crypto module https://nodejs.org/docs/latest/api/crypto.html
- [ ] Fetch, Async Await https://webbutveckling2.gitbook.io/hem/resurser/2.2-async-and-await
