### ISSUE TITLE
Läxa

### ISSUE THREAD

**Issue by JohanG2012** [Wiktorsson/DiscordGyA#32]
E1 till E17 här -> https://webbserverprogrammering1.gitbook.io/project/ det bör vara rätt enkelt för dig och gå rätt snabbt, då det mest är repetition av det du bör ha lärt dig i webbserverprogrammering 1 E1 till E4 är bara läsa lite, E5 bör du kunna efter att ha jobbat med boten, E6 till E12 är bara att skriva av lite kod, tar kanske 30-60min, och E13-E16 så ska du lösa en uppgift tar kanske 1-3h

**Comment by Wiktorsson** [comment]
sry
